parameters:
  pool: 'macOS-latest'
  parentJobs: []
  name: 'mac'

jobs:
- job: ${{ parameters.name }}_packaging
  dependsOn:
    ${{ parameters.parentJobs }}
  pool:
    vmImage: ${{ parameters.pool }}

  displayName: ${{ parameters.name }} Packaging

  steps:
  - powershell: |
      Get-ChildItem -Path env:
    displayName: Capture environment
    condition: succeededOrFailed()

  - template: /tools/releaseBuild/azureDevOps/templates/insert-nuget-config-azfeed.yml

  - powershell: |
      [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12
      Import-Module .\tools\ci.psm1
      Invoke-CIInstall
    displayName: Bootstrap
    condition: succeededOrFailed()

  - powershell: |
      Import-Module .\tools\ci.psm1
      New-CodeCoverageAndTestPackage
      Invoke-CIFinish -NuGetKey $(NUGET_KEY)
    displayName: CodeCoverage and Test Package
